spring:
  datasource:
    url: jdbc:mysql://localhost:3306/judge_ums?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: executor
    password: 123456
  application:
    name: tik-online-judge-auth
tik-online-judge-auth:
  secure:
    secretKey: A*&*(sd.12+-asBN
    algorithm: AES
  user:
    super-admin:
      username: admin
      password: admin
      avatar: https://z3.ax1x.com/2021/09/11/4SEo8O.png
    user-default:
      avatar: https://z3.ax1x.com/2021/09/11/4SEo8O.png
server:
  port: 13000
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    check: false
    version: 0.0.1
    cloud:
      #    订阅服务，订阅多个使用 "," 分割
      subscribed-services: tik-online-judge-message
  scan:
    base-packages: top.adxd.tikonlinejudge.auth
  provider:
    version: 0.0.1
