spring:
  datasource:
    url: jdbc:mysql://tik-mysql:3306/judge_ums?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  redis:
    database: 0
    host: tik-redis
    port: 6379
  rabbitmq:
    host: tik-rabbitmq
    port: 5672
    username: executor
    password: 123456
  application:
    name: tik-online-judge-auth
  cloud:
    config:
      discovery:
        server-addr: tik-nacos:8848
    nacos:
      discovery:
        server-addr: tik-nacos:8848
tik-online-judge-auth:
  secure:
    secretKey: A*&*(sd.12+-asBN
    algorithm: AES
  user:
    super-admin:
      username: admin
      password: admin
      avatar: https://z3.ax1x.com/2021/09/11/4SEo8O.png
    user-default:
      avatar: https://z3.ax1x.com/2021/09/11/4SEo8O.png
server:
  port: 8888
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://tik-nacos:8848
  consumer:
    check: false
    version: 0.0.1
    cloud:
      #    订阅服务，订阅多个使用 "," 分割
      subscribed-services: tik-online-judge-message

  scan:
    base-packages: top.adxd.tikonlinejudge.auth.service.impl
  provider:
    version: 0.0.1
#debug: true