server:
  port: 12000
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: executor
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  application:
    name: tik-online-judge-message
  cloud:
    config:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    check: false
    version: 0.0.1
  #  cloud:
  #    #    订阅服务，订阅多个使用 "," 分割
  #    subscribed-services: tik-online-judge-auth
  scan:
    base-packages: top.adxd.tikonlinejudge.message.service.impl
  provider:
    version: 0.0.1
