server:
  port: 8500
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/judge_ums?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  mail:
    from: TikOnlineJudge@163.com
    host: smtp.163.com
    username: TikOnlineJudge@163.com
    password: UPDRUHZHKVPWKHJL
    #    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          port: 994
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        display:
          sendmail: Javen
          sendname: TikOnlineJudge@163.com
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  application:
    name: tik-online-judge-user
  cloud:
    config:
      discovery:
        server-addr: 127.0.0.1:8848
debug: false
tik-online-judge-user:
  super-admin:
    username: admin
    password: admin
    avatar: https://z3.ax1x.com/2021/09/11/4SEo8O.png
  user-default:
    avatar: https://z3.ax1x.com/2021/09/11/4SEo8O.png
dubbo:
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: top.adxd.tikonlinejudge.user.api.impl
  provider:
    version: 0.0.1
