server:
  port: 8500
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/judge_ums?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  mail:
    from: TikOnlineJudge@163.com
    host: smtp.163.com
    username: TikOnlineJudge@163.com
    password: UPDRUHZHKVPWKHJL
    #    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          port: 994
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        display:
          sendmail: Javen
          sendname: TikOnlineJudge@163.com
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
debug: false
tik-online-judge-user:
  super-admin:
    username: admin
    password: admin
    avatar: https://imgtu.com/i/4SEo8O
  user-default:
    avatar: https://imgtu.com/i/4SEo8O