spring:
  devtools:
    restart:
      enabled: true
  application:
    name: tik-online-judge-gateway
  cloud:
    config:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - PUT
#              - DELETE
#              - POST
#              - OPTION
#            allowedHeaders:
#              - token
#              - DNT
#              - X-Mx-ReqToken
#              - Keep-Alive
#              - User-Agent
#              - X-Requested-With
#              - If-Modified-Since
#              - Cache-Control
#              - Content-Type
#              - Authorization
#        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        #        - id: test
        #          uri: https://www.baidu.com
        #          predicates:
        #            - Query=green
        - id: auth
          uri: lb://tik-online-judge-auth
          predicates:
            - Path=/auth/**
        - id: executor
          uri: lb://tik-online-judge-executor
          predicates:
            - Path=/executor/**
        - id: social
          uri: lb://tik-online-judge-social
          predicates:
            - Path=/social/**
        - id: thirdpart
          uri: lb://tik-online-judge-thirdpart
          predicates:
          - Path=/thirdpart/**
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    check: false
    version: 0.0.1
  cloud:
    #    订阅服务，订阅多个使用 "," 分割
    subscribed-services: tik-online-judge-auth
#  scan:
#    base-packages: top.adxd.tikonlinejudge.executor.api.impl
server:
  port: 10000